# Uso de Dataframe en Pandas
##### https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

In [1]:
import pandas as pd
import sys
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

%matplotlib inline

In [2]:
mi_df = pd.read_json('data/data-demo-2.json')

In [3]:
mi_df

    nombres apellidos
0      rené  elizalde
1   enrique     cueva
2    carlos  castillo
3     pedro   salinas
4  cristian   andrade

In [4]:
mi_df['nombres']

0        rené
1     enrique
2      carlos
3       pedro
4    cristian
Name: nombres, dtype: object

In [5]:
mi_funcion = lambda x: x.upper()
mi_df['nombres-mayuscula'] = mi_df['nombres'].apply(mi_funcion)
mi_df['apellidos'] = mi_df['apellidos'].apply(lambda x: x.upper())

In [6]:
mi_df

    nombres apellidos nombres-mayuscula
0      rené  ELIZALDE              RENÉ
1   enrique     CUEVA           ENRIQUE
2    carlos  CASTILLO            CARLOS
3     pedro   SALINAS             PEDRO
4  cristian   ANDRADE          CRISTIAN

In [7]:
def count_nombres(x):
    valor = len(x)
    return valor

In [21]:
def count_apellidos(x):
    valor = len(x)
    if valor > 3:
        valor = 3
        
    return valor

In [22]:
def primera(x):   
    return x[0]

In [23]:
mi_df['longitud-nombres'] = mi_df['nombres'].apply(count_nombres)
mi_df['longitud-apellidos'] = mi_df['apellidos'].apply(count_apellidos)
mi_df['PrimeraLetraapellidos'] = mi_df['apellidos'].apply(primera)

In [24]:
mi_df

,nombres,apellidos,nombres-mayuscula,longitud-nombres,longitud-apellidos,PrimeraLetraapellidos
0,rené,ELIZALDE,RENÉ,4,3,E
1,enrique,CUEVA,ENRIQUE,7,3,C
2,carlos,CASTILLO,CARLOS,6,3,C
3,pedro,SALINAS,PEDRO,5,3,S
4,cristian,ANDRADE,CRISTIAN,8,3,A